//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilmGenres
    {
        public int FilmId { get; set; }
        public int GenreId { get; set; }
        public int ID { get; set; }
    
        public virtual Films Films { get; set; }
        public virtual Genres Genres { get; set; }
    }
}
